version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
      entrypoint: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    depends_on:
      - db 

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tmQCZVBbxdsdhlWurEdNCPWugNDZJoer
      MYSQL_DATABASE: railway
      MYSQL_USER: miguelf24
      MYSQL_PASSWORD: tmQCZVBbxdsdhlWurEdNCPWugNDZJoer
    ports:
      - "3306:3306"
